name: Deploy Angular to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: bonheur.client

      - name: Build Angular project
        run: npm run build --prod
        working-directory: bonheur.client

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t bonheur.client:latest -f bonheur.client/Dockerfile .
          docker tag bonheur.client:latest ${{ secrets.DOCKER_USERNAME }}/bonheur.client:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bonheur.client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/bonheur.client:latest
            docker stop bonheur.client || true
            docker rm bonheur.client || true
            docker run -d --name bonheur.client \
              -p 4200:4200 \
              ${{ secrets.DOCKER_USERNAME }}/bonheur.client:latest
          EOF
